---
- name: install nginx
  package:
    name: nginx
    state: latest
  become: yes
- name: copy index.html
  copy:
    src: ../SourceFiles/linux_index.html
    dest: /usr/share/nginx/html/index.html
    mode: '644'
  become: yes
- name: set nginx to own /usr/share/nginx
  file:
    path: /usr/share/nginx
    recurse: yes
    owner: nginx
    group: nginx
  become: yes
- name: start nginx service
  service:
    name: nginx
    state: started
  become: yes